[package]
name = "flux-gw"
version = "0.1.0"
edition = "2021"

[dependencies]
flux-auth-api = { path = "../flux-auth/lib/api" }

anyhow = "1.0.89"
config = { version = "0.14", default-features = false, features = ["toml"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

axum = "0.7.6"

tokio = { version = "1.40.0", features = ["full"] }

tonic = { version = "0.12.2", default-features = false, features = ["channel"] }
