[package]
name = "flux-gw"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
flux-auth-api = { git = "https://github.com/thefluxapp/flux-auth.git" }
flux-core-api = { git = "https://github.com/thefluxapp/flux-core.git" }

anyhow = "1.0.91"
config = { version = "0.14", default-features = false, features = ["toml"] }
uuid = { version = "1.11.0", features = ["serde", "v7"] }
jsonwebtoken = "9.3.0"

axum = "0.7.7"
axum-extra = { version = "0.9.4", features = ["typed-header"] }

tokio = { version = "1.41.0", features = ["full"] }

tonic = { version = "0.12.3", default-features = false, features = ["channel"] }

serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
